# These are supported funding model platforms

# github: [user1, user2]
# patreon: user
# open_collective: username
# ko_fi: username
# tidelift: platform-name/package-name
# lfm: username
# buy_me_a_coffee: username
# issuehunt: username
# otechie: username
# custom: ['https://example.com']
